### ISSUE TITLE
我在想这个是每日奖励还是长期的

### ISSUE THREAD

**Issue by ZherKing** [carm-outsource/TimeReward#10]
**问题简述**

![MEUM}IWF6CB1{96$(LKWK5D](https://github.com/carm-outsource/TimeReward/assets/49807821/c22bdf29-df49-48ae-a8f1-1e7cb378a6e4)

**问题来源**

发现每天加入游戏 游玩一定时间都没有提示在线奖励
看了下 /tr user xxxx 发现时间是长期并不是一天内的
我发现并没有进行
**预期结果**(可选)

**问题截图/问题报错**

**操作环境**

2.2.1
**其他补充**

**Comment by CarmJos** [comment]
本插件基于累积的总在线时长给予奖励。
