### ISSUE TITLE
希望可以添加自动领取签到奖励的开关

### ISSUE THREAD

**Issue by ZherKing** [carm-outsource/TimeReward#4]
**功能简述**

自动领取能不能设置成一个开关 也就是说可以手动领取和自动领取
**需求来源**

因为我试图用菜单把他结合进去 但是条件冲突（正好就是自动领取输出内容冲突）
如果把这个问题解决完后我觉得可以更好的让这个插件结合在菜单中
**功能参考**(可选)

**附加内容**

%TimeReward_claimed_<奖励ID>% 领取之前输出为false 时间到后当玩家领取该奖励后 才能输出true
可以考虑不用NMS之类的 避免以后更新版本插件再次不兼容等等
我认为你这个插件基本解决了其他插件中的NMS问题

**Comment by CarmJos** [comment]
该功能将在 [2.1.0]() 版本后支持。

该版本新增 `%TimeReward_claimable_<奖励ID>%` 变量，以得到玩家是否可以领取某个奖励。

并提供了玩家可执行的 `/tr claim [奖励ID]` 指令，用于玩家手动领取奖励。此处“奖励ID”若不填写，则将自动为玩家领取全部可以领取的奖励。

**Comment by CarmJos** [comment]
@Yurinann 请问能否帮助测试一下此功能呀？ 构建地址 https://github.com/carm-outsource/TimeReward/actions/runs/4245444895 。

**Comment by Yurinann** [comment]
> @Yurinann 请问能否帮助测试一下此功能呀？ 构建地址 https://github.com/carm-outsource/TimeReward/actions/runs/4245444895 。

好的，我稍后去测试～

**Comment by Yurinann** [comment]
> @Yurinann 请问能否帮助测试一下此功能呀？ 构建地址 https://github.com/carm-outsource/TimeReward/actions/runs/4245444895 。

目前测试环境下所有功能均可正常使用！

**Comment by CarmJos** [comment]
> > @Yurinann 请问能否帮助测试一下此功能呀？ 构建地址 https://github.com/carm-outsource/TimeReward/actions/runs/4245444895 。
> 
> 目前测试环境下所有功能均可正常使用！

感谢您在百忙之中帮助测试，我稍后将发2.1.0版本。
