### ISSUE TITLE
无法执行timereward claim命令

### ISSUE THREAD

**Issue by ZherKing** [carm-outsource/TimeReward#9]
**问题简述**

无法执行 tr claim 命令 显示结果为没权限
**问题来源**

输入  /tr claim 30 领取一个叫 ”30“ 的在线奖励
但是显示需要 timereward.admin 的权限
这个权限给了不就...全都给了嘛
**预期结果**(可选)

**问题截图/问题报错**

![9HR`R{E`K@NZ_($JCPMC}V](https://user-images.githubusercontent.com/49807821/232284203-ba90f02f-6cf5-4d40-8fd1-fcd596db798e.png)

**操作环境**

TimeReward-2.2.0.jar
Paper-1.19.3 448
**其他补充**

**Comment by CarmJos** [comment]
您好，请 [点击这里](https://github.com/carm-outsource/TimeReward/actions/runs/4712398818) 下载构件后测试。

**Comment by ZherKing** [comment]
> 您好，请 [点击这里](https://github.com/carm-outsource/TimeReward/actions/runs/4712398818) 下载构件后测试。

![AIX`BN8{)EM4 RDB2ICE562](https://user-images.githubusercontent.com/49807821/232288227-1c8929ca-615b-4387-9dec-110eb4f574a0.png)
如图 测试成功 可以进行发布了

**Comment by CarmJos** [comment]
好的，我稍后发版，祝您生活愉快。
